[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = platformio/espressif32@6.12.0
board = esp32dev
framework = arduino
lib_deps = file://../..
build_flags =
    -DLS_MAX_EVENT_SIZE=768
    -DLS_SPOOL_MAX_RECORDS=4
