[platformio]
default_envs = esp32dev
src_dir = main

[env:esp32dev]
platform = platformio/espressif32@6.12.0
board = esp32dev
framework = espidf
board_build.partitions = partitions.csv
monitor_speed = 115200
