find_package(Git QUIET)
set(_git "nogit")
if(Git_FOUND)
  execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse --verify HEAD WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" OUTPUT_VARIABLE _git OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
endif()
file(GLOB_RECURSE _sources CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/include/*.h" "${CMAKE_CURRENT_SOURCE_DIR}/src/*.c" "${CMAKE_CURRENT_SOURCE_DIR}/arch/*.c" "${CMAKE_CURRENT_SOURCE_DIR}/arch/*.S")
set(_seed "${PROJECT_VERSION}:${_git}")
foreach(_source IN LISTS _sources)
  file(SHA256 "${_source}" _hash)
  string(APPEND _seed ":${_hash}")
endforeach()
string(SHA256 LS_GENERATED_BUILD_ID "${_seed}")
string(SUBSTRING "${LS_GENERATED_BUILD_ID}" 0 32 LS_GENERATED_BUILD_ID)
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated/laststate")
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/cmake/build_id_generated.h.in" "${CMAKE_CURRENT_BINARY_DIR}/generated/laststate/build_id_generated.h" @ONLY)
