name: Dependency vulnerability bot
on:
  push:
    branches: [prod]
  pull_request:
  merge_group:
  schedule:
    - cron: '47 8 * * 4'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  scan-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Scan dependencies for known vulnerabilities
        uses: google/osv-scanner-action/osv-scanner-action@9fd1bcce27f67e3bd819a0a7620e332803dc43bc
        with:
          scan-args: |-
            --recursive
            ./
