[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = platformio/espressif32@6.12.0
board = esp32dev
framework = espidf
board_build.partitions = partitions.csv
monitor_port = COM3
monitor_speed = 115200
upload_port = COM3
build_flags =
    -DLS_MAX_EVENT_SIZE=768
    -DLS_SPOOL_MAX_RECORDS=4
    -DLS_BREADCRUMB_CAPACITY=8
    -DLS_METRIC_CAPACITY=8
